modLoader="javafml"

loaderVersion="[40,)"
license="BSD-3-Clause"

[[mods]]
modId="slide_show"
version="${file.jarVersion}"
displayName="Slide Show"

# We will come back later.
credits="ustc_zzzz, BloCamLimb"

authors="3TUSK"

description="Simple slide show projector in Minecraft."
